### ISSUE TITLE
mold cleaning form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#72]
total hours is incorrect should be total of service engineer 1-3

**Comment by nishant-njs** [comment]
Already working...

![resolved](https://cloud.githubusercontent.com/assets/7536874/7044759/89165410-de14-11e4-8b02-7b5b894711e5.jpg)

**Comment by philolsonjr** [comment]
not correct

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7090735/b82c7516-df6a-11e4-8482-58074e993f14.PNG)
value still not correct

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
